name: TestBuild

on:
  push:
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

env:
  IMAGE_NAME: l-smash

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2
      - name: Debugging
        run: |
          echo "${{ github.ref }}" 
          echo "${{ github.event.head_commit.message }}" 
      - name: Prepare Env
        run: |
          apt update && apt install -y git build-essential autoconf automake dos2unix
          dos2unix configure && chmod +x configure
      - name: Build
        run: |
            mkdir -p ./build/bin
            mkdir -p ./build/lib
            mkdir -p ./build/include
            ./configure --prefix='./build' --enable-shared --disable-static
            make install